#!/usr/bin/env bash

# avoid some errors
touch favicon.ico
touch apple-touch-icon.png
touch apple-touch-icon-precomposed.png

# Start an HTTP server from a directory, optionally specifying the port

# Usage:
# ./serve or ./serve 1234

function serve() {
	local port="${1:-8080}";
	sleep 1 && open "http://localhost:${port}/" #&

	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)

    $(python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port";)
}

port="${1:-8080}";
npx -y http-server -p $port #-o 2>/tmp/serve.log || echo "install npx"
